[package]
name = "column-sketch-core"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.17"

[dev-dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }
rstest = "0.18.2"
