[package]
name = "column-sketch-core"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }
rand_distr = "0.4.3"
rstest = "0.18.2"
